### ISSUE TITLE
No implemententions Error

### ISSUE THREAD

**Issue by oscarshaitan** [Joran-Dob/spotify-playback-flutter#14]
I installed the plugin and when run the example I get
`MissingPluginException(No implementation found for method connectSpotify on channel spotify_playback)`

I have all the spotify data and I have registered the app

**Comment by Joran-Dob** [comment]
Hi @oscarshaitan , 

1. Does it fail on iOS, Android, or both?
2. Have you executed flutter run targeting that platform since you changed the pubspec file? This is needed to have Flutter inject plugin dependencies into the platform-specific parts of your app. 

**Please note that hot restart/hot reload is not enough to trigger the injection.**

**Comment by oscarshaitan** [comment]
Hi Im testing on Android at the moment, Let me try the point 2 but Im pretty sure that I did that

**Comment by oscarshaitan** [comment]
Other Question I create a new project to test again and get the following error 

```
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.0 and higher.
The following dependencies do not satisfy the required version:
project ':spotify_playback' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.51
```

**Comment by zacwolfe** [comment]
I'm seeing the `MissingPluginException(No implementation found for method connectSpotify on channel spotify_playback)` issue as well. Does the spotify app need to be installed on the device?

**Comment by zacwolfe** [comment]
My bad, I see there's a native component which is probably why I'm seeing the error. FYI I am also seeing the gradle build error that oscarshaitan noted above.

**Comment by oscarshaitan** [comment]
> My bad, I see there's a native component which is probably why I'm seeing the error. FYI I am also seeing the gradle build error that oscarshaitan noted above.

How did you solve the first issue?

**Comment by Joran-Dob** [comment]
@oscarshaitan @zacwolfe for the issue related to the Kotlin requirements (Kotlin dependency mismatch) I created a separate issue #15

**Comment by Joran-Dob** [comment]
@zacwolfe yes the Spotify app should be installed as this package uses the Spotify Playback SDK for Android which requires the app to be installed.

**Comment by Joran-Dob** [comment]
Did you try this? @oscarshaitan 
> Please note that hot restart/hot reload is not enough to trigger the injection.

**Comment by zacwolfe** [comment]
Thanks @Joran-Dob, and I assume the same is true for iOS, correct?

**Comment by oscarshaitan** [comment]
@Joran-Dob I guess the problem related to the SDK, nowhere says that you need Spotify to be installed.  let try that :D  👍

**Comment by Joran-Dob** [comment]
@zacwolfe yes the same is correct for iOS but for now, there is no iOS implementation yet for this package this is a WIP.

**Comment by Joran-Dob** [comment]
> @Joran-Dob I guess the problem related to the SDK, nowhere says that you need Spotify to be installed. let try that :D 👍

I updated the readme with a warning that the Spotify app should be installed.

**Comment by oscarshaitan** [comment]
Awesome!, I will try later ( the job are intense by this days) but +10 for the help any case

**Comment by Joran-Dob** [comment]
Please try the new version on pub [0.0.7](https://pub.dartlang.org/packages/spotify_playback#-readme-tab-) the Kotlin error should be fixed here. 

Thanks! 🙏
