### ISSUE TITLE
Crashing on UserNotAuthorizedException

### ISSUE THREAD

**Issue by zacwolfe** [Joran-Dob/spotify-playback-flutter#16]
**Describe the bug**
Getting UserNotAuthorizedException on SpotifyPlayback.spotifyConnect() with valid clientID and redirectUrl, causing crash.

**To Reproduce**
1. Try to run example on android with Spotify installed
2. See UserNotAuthorizedException in terminal, note that app crashes

**Expected behavior**
App should trigger track playback in spotify app.

**Smartphone (please complete the following information):**
 - Device: Google Pixel XL
 - OS: Android 9

 - Version: spotify-playback 0.0.6

**Additional context**
There's really 2 issues here:

1. Why am I getting the UserNotAuthorizedException even though I am providing valid clientID and redirect URL and seem to be configured correctly according to this: https://developer.spotify.com/documentation/android/quick-start/

2. Why is that exception causing the flutter app to crash?

Thanks!

**Comment by Joran-Dob** [comment]
Thanks for reporting this issue @zacwolfe can you maybe please attach the error log?

**Comment by Joran-Dob** [comment]
Could not reproduce! Does the example work for you? @zacwolfe
