### ISSUE TITLE
iOS Implementation of the Spotify Playback SDK WIP

### ISSUE THREAD

**Issue by Joran-Dob** [Joran-Dob/spotify-playback-flutter#17]
**Describe the solution you'd like**
Implementation of the Spotify Playback SDK for iOS, so the package can be used for both Android an iOS.

**Additional context**
* Feel free to make a pull request, all help is welcome.
* Might need a real device to make this implementation.

Related #14

**Comment by jifalops** [comment]
How's it going, any updates?

**Comment by marioolislaegers** [comment]
Is it still being worked on?
