### ISSUE TITLE
SpotifyConnectionTerminatedException

### ISSUE THREAD

**Issue by BMXsanko** [Joran-Dob/spotify-playback-flutter#20]
**Describe the bug**
The bug occurs when I leave the example app open for a longer period of time(without doing anything) then it randomly crashes.
**To Reproduce**
Leave the app open without interaction

@Joran-Dob could you tell if this is only for me or is it something that happens to you as well?

**Comment by Joran-Dob** [comment]
@BMXsanko ohhhh, no this did not happen to me yet. Are you using the current pub version? 0.0.7? If not please try that! I will check the push request this afternoon could it be related? :flushed:

**Comment by Joran-Dob** [comment]
@BMXsanko is this issue still reproducible for you or can it be closed? 😄

**Comment by furkansarihan** [comment]
SpotifyConnectionTerminatedException crashes my app too.

**Comment by Joran-Dob** [comment]
@furkansarihan did you follow the setup for the example?
