### ISSUE TITLE
v0.0.7 kotlin error

### ISSUE THREAD

**Issue by oscarshaitan** [Joran-Dob/spotify-playback-flutter#22]
On the new version I got the following error

```
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not find :spotify-app-remote-release-0.6.1:.
     Searched in the following locations: file:/D:/FlutterProjects/.../android/app/libs/spotify-app-remote-release-0.6.1.aar
     Required by:
         project :app > project :spotify_playback
```

I do the get and the update  Packages

**Comment by BMXsanko** [comment]
Hi @oscarshaitan can you tell me if you are working in the example directory or in your own project? If you are working in you own project you just have to add `spotify-app-remote-release-0.6.1.aar` to the `android/libs/` folder in your project. You can get the .aar file from this repo in `android/libs/`  or from the official spotify android SKD github page: [here](https://github.com/spotify/android-sdk/releases/tag/v0.6.1-appremote_v1.1.0-auth).

**Comment by oscarshaitan** [comment]
thats all, I need
a small correction the rigth path is \android\app\libs\spotify-app-remote-release-0.6.1.aar

please add that to the README  ;) +10 again thx guys

**Comment by Joran-Dob** [comment]
Updated the readme see this [commit](https://github.com/qreate/spotify-playback-flutter/commit/e6c7840936236718b5c1db99da7d903d50c74fa8)
