### ISSUE TITLE
getImage function slows down ui

### ISSUE THREAD

**Issue by BMXsanko** [Joran-Dob/spotify-playback-flutter#23]
The getImage function I added a few days ago is working fine, but it slows down the UI a lot, especially when you request a lot of images at once. I am not really sure whether the slowdown happens on the Dart side or on the Kotlin side... @Joran-Dob any idea why this might be?

**Comment by Joran-Dob** [comment]
I will look into optimizing this functionality in the scope of release [v0.1.0](https://github.com/qreate/spotify-playback-flutter/milestone/3). Probably it's nice to move some of part of this implementation from Kotlin to Dart if possible. Might improve performance.

I will probably also add a warning to the readme that it can slow down the UI. when using this functionality.

**Comment by Joran-Dob** [comment]
Added the warning to readme linked to this issue. ✈️

**Comment by BMXsanko** [comment]
@Joran-Dob thanks!  I will also look into some possible solutions.

**Comment by BMXsanko** [comment]
OK, I discovered that the issue is on the Kotlin side of the code, the issue is that you can't just send the image "as is" because it is a Bitmap which is not supported by flutter, and the conversion takes a while.

**Comment by Joran-Dob** [comment]
@BMXsanko awesome, I might have some time tomorrow to look into optimization of this conversion

**Comment by BMXsanko** [comment]
@Joran-Dob I have looked into the issue I tried wrapping the getImage() method into the compute() function, which puts the function you assign it on a separate isolate, this, in theory, should have solved the issue but then I discovered this: https://github.com/flutter/flutter/issues/13937

**Comment by BMXsanko** [comment]
Ok, I made a PR regarding this issue, I didn't have time to fully test it, on the first look it seems to improve performance.

**Comment by Joran-Dob** [comment]
Merged the pull request. I will also merge some changes I made in a bit. And afterwards, close this issue! Thanks for your awesome work 😎

**Comment by mvarendorff** [comment]
Does that mean the warning may be removed from the readme as well?
