### ISSUE TITLE
INVALID_CLIENT

### ISSUE THREAD

**Issue by oscarshaitan** [Joran-Dob/spotify-playback-flutter#30]
maybe the issue isn't the plugin, and maybe related to the spotify sdk 
when trying to connect I got the next error 
`java.lang.IllegalArgumentException: Unsupported value: com.spotify.android.appremote.api.error.AuthenticationFailedException: {"message":"Client authentication failed:INVALID_CLIENT"}`

there are 2 errors nested, the _java.lang.IllegalArgumentException_ I guess is the plugin but the other one _AuthenticationFailedException_ 

Any idea to how solve the problems?

I have the Id from the spotify sdk config and, have the aar. on the libs

**Comment by Joran-Dob** [comment]
Hi @oscarshaitan, 

Are you trying to run the example or implementing this plugin in your own project?

**Comment by oscarshaitan** [comment]
Im working on my implementation, but practically I copied the example

**Comment by Joran-Dob** [comment]
Did you register the app correctly with Spotify? see: example/README.md

**Comment by oscarshaitan** [comment]
Yes and I have the Client ID, I check that yesterday too.
even on the spotify SDK there is a issue similar

**Comment by Joran-Dob** [comment]
@oscarshaitan Could you maybe reference the issue in the Spotify SDK? Then I will check it out!

**Comment by oscarshaitan** [comment]
sure, [https://github.com/spotify/android-sdk/issues/55](https://github.com/spotify/android-sdk/issues/55)

**Comment by Joran-Dob** [comment]
@oscarshaitan does the example work correctly for you when you follow the steps from the readme?
