### ISSUE TITLE
subscribeToPlayerState() for one event seems overkill

### ISSUE THREAD

**Issue by benoitjadinon** [Joran-Dob/spotify-playback-flutter#31]
**Is your feature request related to a problem? Please describe.**
Correct me if I'm wrong but given the current dart api is more of a pull/poll-based one atm, I think you should use `getPlayerState()` instead of `subscribeToPlayerState()` on the kotlin side.
see https://developer.spotify.com/documentation/android/guides/making-remote-calls/
cause I think it 'leaks' a subscription for future events, when we only need one response, am I right ?

**Describe the solution you'd like**
Use `getPlayerState` ;-)

**Describe alternatives you've considered**
Susbcribing once kotlin side with `subscribeToPlayerState`, and pushing updates to dart

**Comment by benoitjadinon** [comment]
something like https://github.com/benoitjadinon/spotify-playback-flutter/commit/e759a5475bbc84a9896d1804b989a040bd0152c3

**Comment by Joran-Dob** [comment]
@benoitjadinon Thanks, Benoit. I think you are correct about this part 

> cause I think it 'leaks' a subscription for future events, when we only need one response, am I right ?

The plan is to implement some kind of dart push on change. 

I will have a look!

**Comment by benoitjadinon** [comment]
wanted to PR it myself, but I keep delaying my Kotlin class ;-)
