### ISSUE TITLE
crash when connect to spotify

### ISSUE THREAD

**Issue by liodali** [Joran-Dob/spotify-playback-flutter#33]
hi,
when i try to connect with SpotifyPlayback.spotifyConnect
it crash and show me this message :
com.spotify.protocol.client.error.RemoteClientException: {"message":"com.spotify.mobile.android.spotlets.appprotocol.model.AppProtocol$Message"}

**Comment by Joran-Dob** [comment]
@liodali did you follow the setup for the example?

**Comment by liodali** [comment]
yes i follow the exemple and i even native sdk it show me that message

**Comment by gytd** [comment]
Please reopen this ticket. I had the same message. I tried the sample project multiple times. With the auth lib (https://developer.spotify.com/documentation/android/quick-start/#register-application-fingerprints) and without it (https://developer.spotify.com/documentation/android/guides/android-authentication/).
I used the newest SDK (android-sdk-0.6.2-appremote_v1.1.0-auth), but I also had a try with an older package (android-sdk-0.6.1-appremote_v1.1.0-auth). I searched about it, and this was the only link I found on google. It looks like a server-side issue to me (the error message definitely). I think the reason could be a new change on the server-side.
Maybe I made a mistake, but this message didn't help too much. :(

**Comment by gytd** [comment]
Sorry, wrong repo. I reported it to here: https://github.com/spotify/android-sdk/issues/132
