### ISSUE TITLE
is getCurrentlyPlayingTrack() not working?

### ISSUE THREAD

**Issue by thorandresen** [Joran-Dob/spotify-playback-flutter#36]
Tried using it, and I can't get it to work, just prints a lot of `Unable to resolve Lcom/spotify/protocol/types/PlaybackPosition; annotation class 183`.

I can't seem to see the implementation in the example either, is it not working correctly?

**Comment by lvinci** [comment]
I am having the same issue

**Comment by lvinci** [comment]
Any updates?

**Comment by Joran-Dob** [comment]
This is probaly due to an outdated spotify SDK, I will look into it.
