### ISSUE TITLE
Issue with importing plugin.

### ISSUE THREAD

**Issue by TarchyV** [Joran-Dob/spotify-playback-flutter#38]
When I install the plugin and run flutter pub get I get this error:

`'C:\Users\$NAME\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\spotify_playback-0.0.8\android\src\main\kotlin\io\feesie\spotify\playback\SpotifyPlaybackPlugin.kt' even though it exists. Please verify that this file has read permission and try again.
exit code 1`

I have been searching for a fix for 2 hours and could not get it to work. I have changed versions of flutter, tried to use the GitHub repository when importing it into my pubsec.yaml, and I tried all the different versions of the plugin and i am getting no luck.

**Comment by Marcelxy** [comment]
I have the same issue.

**Comment by Joran-Dob** [comment]
Fixed by new merge
